apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: grajamca/product:1.0.0
          ports:
            - name: product
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  type: LoadBalancer
  ports:
    - port: 8000
      protocol: TCP
      targetPort: product